### ISSUE TITLE
Forks are confusing

### ISSUE THREAD

**Issue by merlijn-sebrechts** [cloud-green/juju-relation-mongodb#4]
Hi

I'm a bit confused by what the upstream for this repo is. This repo is the one linked on [interfaces.juju.solutions](interfaces.juju.solutions), however, this seems to be a downstream from `cmars/juju-relation-mongodb`. Where should we report bugs and submit pull requests to? Might it be possible to remove one of the repo's to avoid confusion?

Kind regards
Merlijn

**Comment by cmars** [comment]
I would assume that the repo and branch referenced in interfaces.juju.solutions would be the place to open issues and propose pull requests.

I started this interface under my own personal Github account initially, and then forked it into this org once I started collaborating on it with others. Unfortunately, Github shows my repo as an upstream because I forked the project through the Github UI.

I don't want to delete my fork because that's where I'd want to propose my own pull requests from, for future work on this interface. I can try to delete my fork and recreate it empty, and then push back to it. That might get rid of Github's "forked from ..." link. Or maybe there's a way in the project settings. I'll poke at it.

**Comment by cmars** [comment]
Looks like I was able to shake that "forked from ..." link off.

**Comment by merlijn-sebrechts** [comment]
Awesome, thanks! Just curious, how did you do that? I might need to do the
same in a while.

Op dinsdag 12 april 2016 heeft Casey Marshall notifications@github.com
het volgende geschreven:

**Comment by cmars** [comment]
I ended up deleting my fork and re-forking :)
